# Generated by Django 4.1.2 on 2022-10-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='roll_no',
        ),
    ]
