# Generated by Django 4.1.2 on 2022-10-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('technical_language', models.CharField(max_length=50)),
            ],
        ),
    ]
